[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "mrov"
name = "TerminalFormatter"
description = "Rework of terminal's pages."
websiteUrl = "https://github.com/AndreyMrovol/LethalTerminalFormatter"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
mrov-MrovLib = "0.2.1"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../TerminalFormatter/dist"

[[build.copy]]
source = "../TerminalFormatter/bin/Release/netstandard2.1/TerminalFormatter.dll"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[publish]
communities = [ "lethal-company", ]